version: '3'

services:
  jupyter:
    #13/09/2019
    image: jupyter/datascience-notebook:1386e2046833
    networks:
      - dmz
    ports:
      - "8888:8888"
    volumes:
      - /srv/jupyter/work:/home/jovyan/work
      - /srv/jupyter/.jupyter:/home/jovyan/.jupyter
    # environment:
    #   - CONDA_ENVS_PATH=${REPO_HOME}/envs

networks:
  dmz:
    external: true
